Book_Ladder/web/home/__init__.py
# -*- coding = utf-8 -*-
# @Time:2021/3/713:29
# @Author:Linyu
# @Software:PyCharm
from flask import Blueprint

home = Blueprint("home",__name__)
import web.home.views

Book_Ladder/web/home/views.py
# -*- coding = utf-8 -*-
# @Time:2021/3/713:31
# @Author:Linyu
# @Software:PyCharm

from . import home
from flask import flash,redirect,render_template,url_for
# from web import db
# import web
# from web.messege import Message,HelloForm
@home.route("/")
def index():

    return render_template('home/index.html')


# @home.route("/",methods = ['GET','POST'])
# def index():
#     # messages = Message.query(Message.timestamp).all()
#     form = HelloForm()
#     if form.validate_on_submit():
#         name = form.name.data
#         body = form.body.data
#         message = Message(body=body,name=name)
#         db.session.add(message)
#         db.session.commit()
#         flash('Your message have been sent to the BookLadder!')
#         return redirect(url_for('index'))
#     return render_template('home/indexMes.html',form = form)

Book_Ladder/web/templates/home/index.html
<!DOCTYPE html>
<html lang="en">
<head>
<title>BookLadder</title>
<!-- for-mobile-apps -->
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content="" />
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false);
		function hideURLbar(){ window.scrollTo(0,1); } </script>
<!-- //for-mobile-apps -->
<link rel="shortcut icon" href="../../static/icon/fav.ico" type="image/x-icon"/>
 <link rel="icon" href="../../static/icon/fav.ico" type="image/x-icon"/>
<link href="../../static/assetOne/css/bootstrap.css" rel="stylesheet" type="text/css" media="all" />
<link href="../../static/assetOne/css/style.css" rel="stylesheet" type="text/css" media="all" />
<link href="../../static/assetOne/css/font-awesome.min.css" rel="stylesheet" type="text/css" media="all">
<link rel="stylesheet" href="../../static/assetOne/css/lightbox.css">
<link href="../../static/assetOne/css/team.css" rel="stylesheet" type="text/css">

<!--web-fonts-->
<link href="http://fonts.googleapis.com/css?family=Rubik:300,300i,400,400i,500,500i,700,700i,900,900i" rel="stylesheet">
<link href="http://fonts.googleapis.com/css?family=Lato:300,400,700" rel="stylesheet">
<!--//web-fonts-->
<!--//fonts-->
</head>



<body>
<div class="banner-w3layouts" id="home">
		<!--Top-Bar-->
	<div class="header">
		<nav class="navbar navbar-default">
					<div class="navbar-header">
						<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
							<span class="sr-only">Toggle navigation</span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
						</button>
						<h1><a href="/">Book Ladder</a>
{#                            <a style="font-size: 10px">高尔基</a>#}
                        </h1>
					</div>

					<!-- navbar-header -->
					<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
						<ul class="nav navbar-nav navbar-right">
							<li><a class="hvr-underline-from-center active scroll" href="{{ url_for('home.index') }}">
                                主页
                            </a></li>
                            <li><a class="" href="{{ url_for('book.listPage') }}">
                                书单
                            </a></li>
                            <li><a class="" href="{{ url_for('book.heart') }}">
                               随心
                            </a></li>
                            <li><a class="" href="{{ url_for('book.bookgreat') }}">
                                浩瀚
                            </a></li>
                            <li><a class="" href="{{ url_for('page.analyse') }}">
                                书海
                            </a></li>

						</ul>
					</div>
					<div class="clearfix"> </div>	
				</nav>
	
	</div>
		<!--//Top-Bar-->
<!--banner-->
		<!--Slider-->
			<div class="w3l_banner_info">
				<div class="col-md-7 slider">
					<div class="callbacks_container">
								<ul class="rslides" id="slider3">
									<li>
										<div class="slider_banner_info">
											 <h4 class="test">书单</h4>
                                            <p>热门类别书籍精心挑选展示,真实数据支持，权威人士推荐，只选最热门，只选最好评</p>
										</div>

									</li>
									<li>
										<div class="slider_banner_info">
											 <h4 class="test">随心</h4>
											<p>完美匹配您的选择困难症，输入任意关键字，上百本高分书籍随机推荐一本</p>
										</div>

									</li>
									<li>
										<div class="slider_banner_info">
											 <h4 class="test">浩瀚</h4>
											<p>全网超全书库资源网站汇总，实体购书，二手淘书，电子书资源，mobi、txt、eupb等格式应有尽有</p>
										</div>

									</li>
									<li>
										<div class="slider_banner_info">
											 <h4 class="test">书海</h4>
											<p>可视化展示高分书籍，给您最直观的数据，畅览平台好书</p>
										</div>

									</li>
								</ul>
					</div>
				</div>

		</div>
			<!--//Slider-->
			<div class="clearfix"></div>
</div>
		
<!--//banner-->

<!-- //property -->
<!-- //team -->

<!-- gallery -->
<!-- //gallery -->



<!-- testimonial -->
<!-- //testimonial -->
<div class="footer-final">
		<div class="copyw3-agile"> 
			<div class="container">
				<p>Copyright &copy; 2021.BookLadder All rights reserved.</p>
			</div>
		</div>
	</div>

<!-- js -->
<script type="text/javascript" src="../../static/assetOne/js/jquery-2.1.4.min.js"></script>
<script src="../../static/assetOne/js/SmoothScroll.min.js"></script>
			
<script src="../../static/assetOne/js/lightbox-plus-jquery.min.js"> </script><!-- for gallery js -->
					<!--banner Slider starts Here-->
						<script src="../../static/assetOne/js/responsiveslides.min.js"></script>
							<script>
								// You can also use "$(window).load(function() {"
								$(function () {
								  // Slideshow 4
								  $("#slider3").responsiveSlides({
									auto: true,
									pager:true,
									nav:false,
									speed: 500,
									namespace: "callbacks",
									before: function () {
									  $('.events').append("<li>before event fired.</li>");
									},
									after: function () {
									  $('.events').append("<li>after event fired.</li>");
									}
								  });
							
								});
							 </script>

							<!--banner Slider starts Here-->

<!-- start-smoth-scrolling -->
<script type="text/javascript" src="../../static/assetOne/js/move-top.js"></script>
<script type="text/javascript" src="../../static/assetOne/js/easing.js"></script>
<script type="text/javascript">
	jQuery(document).ready(function($) {
		$(".scroll").click(function(event){		
			event.preventDefault();
			$('html,body').animate({scrollTop:$(this.hash).offset().top},1000);
		});
	});
</script>
<!-- text-effect -->
		<script type="text/javascript" src="../../static/assetOne/js/jquery.transit.js"></script>
		<script type="text/javascript" src="../../static/assetOne/js/jquery.textFx.js"></script>
		<script type="text/javascript">
			$(document).ready(function() {
					$('.test').textFx({
						type: 'fadeIn',
						iChar: 100,
						iAnim: 1000
					});
			});
		</script>
<!-- //text-effect -->

<!-- start-smoth-scrolling -->
<!--//footer-section-->
<!-- smooth scrolling -->
	<script type="text/javascript">
		$(document).ready(function() {
		/*
			var defaults = {
			containerID: 'toTop', // fading element id
			containerHoverID: 'toTopHover', // fading element hover id
			scrollSpeed: 1200,
			easingType: 'linear' 
			};
		*/								
		$().UItoTop({ easingType: 'easeOutQuart' });
		});
	</script>
	<a href="#" id="toTop" style="display: block;"> <span id="toTopHover" style="opacity: 1;"> </span></a>
<!-- //smooth scrolling -->


<script type="text/javascript" src="../../static/assetOne/js/bootstrap-3.1.1.min.js"></script>
</body>
</html>