Book_Ladder/web/book/__init__.py
# -*- coding = utf-8 -*-
# @Time:2021/3/713:30
# @Author:Linyu
# @Software:PyCharm
from flask import Blueprint

book = Blueprint("book",__name__)
import web.book.views

Book_Ladder/web/book/views.py
# -*- coding = utf-8 -*-
# @Time:2021/3/713:31
# @Author:Linyu
# @Software:PyCharm

from . import book
from flask import request,render_template,url_for,session,redirect
from web.models import Modle
from web.models import clean
from web.models import Type
from web.models import Dict
from web.models import FindHeart
from web.models import find_Book
from web.wdCloud import infoCloud
from web.priceSpider import spider
import time

#书单页
@book.route("/list")
def listPage():
    dic = Dict()
    return render_template('book/bookList.html',dic = dic)
    # dic = Dict()
    # return render_template('book/listPage.html',dic = dic)

#类别书单页
@book.route("/<coretype>")
def booklist(coretype):
    coretype = coretype
    sql = "select * from allbook where coretype =  "
    sql = sql +"'"+coretype+"'"
    data = Modle().query(sql)
    #这个是模糊查询
    # data = Modle().query('select * from allbook where coretype = "%'+coretype+'%"')
    datas = clean(data)
    # print(coretype)
    type = Type(coretype)
    return render_template('book/typelist.html',data = datas,typeTitle =type)

#书籍详情页,核心书单详情页
@book.route("bookInfo/<title>")
def bookInfo(title):
    title = title
    data2 = Modle().query('select * from allbook where  title like "%'+title+'%"')
    datas = clean(data2)
    data = datas[0]
    type = data['coretype']
    id_num = data['id_num']
    type = Type(type)
    infoCloud(title)
    time.sleep(1)
    price = spider(data['isbn'])
    return render_template('book/bookinfo.html',title = title,data = data,type = type,price=price,id_num = id_num)


#非核心书单详情页
@book.route("otherBook/<title>")
def otherBook(title):
    title = title
    data2 = Modle().query('select * from allbook where  title like "%'+title+'%"')
    datas = clean(data2)
    data = datas[0]
    price = spider(data['isbn'])
    return render_template('book/otherinfo.html',title = title,data= data,price = price)

#随心
@book.route("/heart",methods = ['GET','POST'])
def heart():
    form = FindHeart()
    if form.validate_on_submit():
        yourheart = form.yourheart.data
        dic = find_Book(yourheart)
        title = dic['title']
        coretype = dic['coretype']
        if coretype:
            return redirect(url_for('book.bookInfo',title=title))
        else:
            return redirect(url_for('book.otherBook',title=title))

    return render_template('book/heart.html', form = form, yourheart = session.get('yourheart'))

#浩瀚
@book.route("/bookgreat")
def bookgreat():
    return render_template('book/bookgreat.html')

Book_Ladder/web/templates/book/baseList.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>BookLadder</title>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="referrer" content="no-referrer">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="../../static/bookList/css/bootstrap.min.css">

    <!-- FontAwesome CSS -->
    <link rel="stylesheet" href="../../static/bookList/css/font-awesome.min.css">

    <!-- Styles -->
    <link rel="stylesheet" href="../../static/bookList/style.css">
    <!-- 放置图标 -->
    <link rel="shortcut icon" href="../../static/icon/fav.ico" type="image/x-icon"/>
    <link rel="icon" href="../../static/icon/fav.ico" type="image/x-icon"/>
    {% block link %}

    {% endblock %}

</head>
<body>
<header class="site-header">
    <div class="site-branding">
        <!-- 这里放置图标和返回主页的链接 -->
        <h1 class="site-title"><a href="{{ url_for('home.index') }}" rel="home"><img src="{{ url_for("static",filename='bookList/images/fav.ico') }}" alt="Logo"></a></h1>
    </div><!-- .site-branding -->

    <div class="hamburger-menu">
        <div class="menu-icon">
            <img src="{{ url_for("static",filename='bookList/images/menu-icon.png') }}"alt="menu icon">
        </div><!-- .menu-icon -->

        <div class="menu-close-icon">
            <img src="{{ url_for("static",filename='bookList/images/x.png') }}" alt="menu close icon">
        </div><!-- .menu-close-icon -->
    </div><!-- .hamburger-menu -->
</header><!-- .site-header -->

<nav class="site-navigation flex flex-column justify-content-between">
    <!-- 设置返回主页 -->
    <div class="site-branding d-none d-lg-block ">
        <!-- 设置图标 -->
        <h1 class="site-title"><a href="{{ url_for('home.index') }}" rel="home"><img src="{{ url_for("static",filename='bookList/images/bookladder.png') }}" alt="Logo"></a></h1>
    </div><!-- .site-branding -->

    <ul class="main-menu flex flex-column justify-content-center">
        <!-- 返回页面设置 -->
        <li><a href="{{ url_for('home.index') }}" class = "special">主页</a></li>
        <li class="current-menu-item"><a href="{{ url_for('book.listPage') }}" class = "special">书单</a></li>
        <li><a href="{{ url_for('book.heart') }}" class = "special">随心</a></li>
        <li><a href="{{ url_for('book.bookgreat') }}" class = "special">浩瀚</a></li>
        <li><a href="{{ url_for('page.analyse') }}" class = "special">书海</a></li>
    </ul>

<p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script>Book Ladder All rights reserved <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://github.com/Rdjroot" target="_blank">Rdjroot</a>
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
</p>


    <div class="social-profiles">
        <ul class="flex justify-content-start justify-content-lg-center align-items-center">
            <!-- 再次设置返回页面 -->
            <li><a href="{{ url_for('book.listPage') }}"><i class="fa fa-book"></i></a></li>
            <li><a href="{{ url_for('book.heart') }}"><i class="fa fa-heart"></i></a></li>
            <li><a href="{{ url_for('book.bookgreat') }}"><i class="fa fa-wrench"></i></a></li>
            <li><a href="{{ url_for('page.analyse') }}"><i class="fa fa-wpexplorer"></i></a></li>
        </ul>
    </div><!-- .social-profiles -->
</nav><!-- .site-navigation -->

<div class="nav-bar-sep d-lg-none"></div>

{% block con %}

{% endblock %}


<!-- 设置静态请求 -->

{% block script %}

{% endblock %}

<script type='text/javascript' src ="{{ url_for("static",filename='bookList/js/jquery.js') }}"></script>
<script type='text/javascript' src="{{ url_for('static',filename = 'bookList/js/custom.js') }}"></script>

</body>
</html>

Book_Ladder/web/templates/book/basebook.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>BookLadder</title>
    <!-- for-mobile-apps -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="referrer" content="no-referrer">
    <meta name="keywords" content="" />
    <script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false);
    function hideURLbar(){ window.scrollTo(0,1); } </script>
    <!-- //for-mobile-apps -->
    <link rel="shortcut icon" href="../../static/icon/fav.ico" type="image/x-icon"/>
    <link rel="icon" href="../../static/icon/fav.ico" type="image/x-icon"/>
    <link href="../../static/assetOne/css/bootstrap.css" rel="stylesheet" type="text/css" media="all" />
    <link href="../../static/assetOne/css/style.css" rel="stylesheet" type="text/css" media="all" />
    <link href="../../static/assetOne/css/font-awesome.min.css" rel="stylesheet" type="text/css" media="all">
    <link rel="stylesheet" href="../../static/assetOne/css/lightbox.css">
    <link href="../../static/assetOne/css/team.css" rel="stylesheet" type="text/css">
{#    另一个css文件引用#}
    <link href="../../static/assetTwo/templatemo_style.css" rel="stylesheet" type="text/css" />
    <!--[endif]-->
    <script src="../../static/assetThree/js/jquery.min.js"></script>
    <!-- jQuery Easing -->
    <script src="../../static/assetThree/js/jquery.easing.1.3.js"></script>
    <!-- Bootstrap -->
    <script src="../../static/assetThree/js/bootstrap.min.js"></script>
    <!-- Waypoints -->
    <script src="../../static/assetThree/js/jquery.waypoints.min.js"></script>
    <!-- Main -->
    <script src="../../static/assetThree/js/main.js"></script>
    <script type="text/javascript" src="../../static/assetOne/js/bootstrap-3.1.1.min.js"></script>
    <script type="text/javascript" src="../../static/assetOne/js/jquery.transit.js"></script>
    <script type="text/javascript" src="../../static/assetOne/js/jquery.textFx.js"></script>
    <script type="text/javascript" src="../../static/assetOne/js/move-top.js"></script>
    <script type="text/javascript" src="../../static/assetOne/js/easing.js"></script>



    {% block link %}

    {% endblock %}

    <!--web-fonts-->
    <link href="http://fonts.googleapis.com/css?family=Rubik:300,300i,400,400i,500,500i,700,700i,900,900i" rel="stylesheet">
    <link href="http://fonts.googleapis.com/css?family=Lato:300,400,700" rel="stylesheet">
    <!--//web-fonts-->
    <!--//fonts-->
</head>



<body>
<div class="banner-w3layouts" id="home">
    {% block banner %}
    <div class="header">
        <nav class="navbar navbar-default">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <h1><a  href="/">Book Ladder</a>
                    {#                            <a style="font-size: 10px">高尔基</a>#}
                </h1>
            </div>

            <!-- navbar-header -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li><a class="" href="{{ url_for('home.index') }}">
                        主页
                    </a></li>
                    <li><a class="" href="{{ url_for('book.listPage') }}">
                        书单
                    </a></li>
                    <li><a class="" href="{{ url_for('book.heart') }}">
                        随心
                    </a></li>
                    <li><a class="" href="{{ url_for('book.bookgreat') }}">
                        浩瀚
                    </a></li>
                    <li><a class="" href="{{ url_for('page.analyse') }}">
                        书海
                    </a></li>

                </ul>
            </div>
            <div class="clearfix"> </div>
        </nav>

    </div>
    <!--//Top-Bar-->
    {% endblock %}

    {% block con %}

    {% endblock %}



<!-- testimonial -->
<!-- //testimonial -->
<div class="footer-final">
    <div class="copyw3-agile">
        <div class="container">
            <p>Copyright &copy; 2021.Company name All rights reserved.</p>
        </div>
    </div>
</div>

<!-- js -->
<script type="text/javascript" src="../../static/assetOne/js/jquery-2.1.4.min.js"></script>
<script src="../../static/assetOne/js/SmoothScroll.min.js"></script>

<script src="../../static/assetOne/js/lightbox-plus-jquery.min.js"> </script><!-- for gallery js -->
<!--banner Slider starts Here-->
<script src="../../static/assetOne/js/responsiveslides.min.js"></script>

<script>
    // You can also use "$(window).load(function() {"
    $(function () {
        // Slideshow 4
        $("#slider3").responsiveSlides({
            auto: true,
            pager:true,
            nav:false,
            speed: 500,
            namespace: "callbacks",
            before: function () {
                $('.events').append("<li>before event fired.</li>");
            },
            after: function () {
                $('.events').append("<li>after event fired.</li>");
            }
        });

    });
</script>

<!--banner Slider starts Here-->

<!-- start-smoth-scrolling -->

<script type="text/javascript">
    jQuery(document).ready(function($) {
        $(".scroll").click(function(event){
            event.preventDefault();
            $('html,body').animate({scrollTop:$(this.hash).offset().top},1000);
        });
    });
</script>
<!-- text-effect -->

<script type="text/javascript">
    $(document).ready(function() {
        $('.test').textFx({
            type: 'fadeIn',
            iChar: 100,
            iAnim: 1000
        });
    });
</script>
<!-- //text-effect -->

<!-- start-smoth-scrolling -->
<!--//footer-section-->
<!-- smooth scrolling -->
<script type="text/javascript">
    $(document).ready(function() {
        /*
            var defaults = {
            containerID: 'toTop', // fading element id
            containerHoverID: 'toTopHover', // fading element hover id
            scrollSpeed: 1200,
            easingType: 'linear'
            };
        */
        $().UItoTop({ easingType: 'easeOutQuart' });
    });
</script>
<a href="#" id="toTop" style="display: block;"> <span id="toTopHover" style="opacity: 1;"> </span></a>
<!-- //smooth scrolling -->


<!--搜索页面的引用-->
    <!-- jQuery -->

</div>
</body>
</html>

Book_Ladder/web/templates/book/bookList.html
{% extends "book/baseList.html" %}

{% block con %}
<div class="outer-container">
    <div class="container portfolio-page">
        <div class="row">
            <div class="col">
                <ul class="breadcrumbs flex align-items-center">
                    <!-- 设置返回主页 -->
                    <li><a href="{{ url_for('home.index') }}">BookLadder</a></li>
                    <li>书单页面</li>
                </ul><!-- .breadcrumbs -->
            </div><!-- .col -->
        </div><!-- .row -->

        <div class="row">
            {% for key in dic.keys() %}
            <div class="col-12 col-md-6 col-lg-3">
            <div class="portfolio-content">
                <figure>
                    <!-- 请求图片 -->
                    <img src="../../static/bookList/images/Dicinfo/{{ key }}.png"  alt="">
                </figure>
                <div class="entry-content flex flex-column align-items-center justify-content-center">
                    <!-- 书单分类 -->
                    <h3 ><a href="{{ url_for('book.booklist',coretype = key) }}">{{ dic[key] }}</a></h3>
                </div><!-- .entry-content -->
            </div><!-- .portfolio-content -->
        </div><!-- .col -->
            {% endfor %}
        </div><!-- .row -->

        <!--
        <div class="scroll-down flex flex-column justify-content-center align-items-center d-none d-lg-block">
            <span class="arrow-down flex justify-content-center align-items-center"><img src="{{ url_for("static",filename='bookList/images/arrow-down.png') }}" alt="arrow"></span>
            <span class="scroll-text">Scroll Down</span>
        </div>
        -->

    </div><!-- .container -->
</div><!-- .outer-container -->
{% endblock %}

Book_Ladder/web/templates/book/heart.html
{% import "bootstrap/wtf.html" as wtf%}
<!DOCTYPE HTML>
<html>
	<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>BookLadder</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="Free HTML5 Website Template by FreeHTML5.co" />
	<meta name="keywords" content="free website templates, free html5, free template, free bootstrap, free website template, html5, css3, mobile first, responsive" />
	<meta name="author" content="FreeHTML5.co" />

  	<!-- Facebook and Twitter integration -->
	<meta property="og:title" content=""/>
	<meta property="og:image" content=""/>
	<meta property="og:url" content=""/>
	<meta property="og:site_name" content=""/>
	<meta property="og:description" content=""/>
	<meta name="twitter:title" content="" />
	<meta name="twitter:image" content="" />
	<meta name="twitter:url" content="" />
	<meta name="twitter:card" content="" />

    <link rel="shortcut icon" href="../../static/icon/fav.ico" type="image/x-icon"/>
    <link rel="icon" href="../../static/icon/fav.ico" type="image/x-icon"/>
	<link href='https://fonts.googleapis.com/css?family=Work+Sans:400,300,600,400italic,700' rel='stylesheet' type='text/css'>
	<link href="https://fonts.googleapis.com/css?family=Playfair+Display:400,700" rel="stylesheet">

	<!-- Animate.css -->
	<link rel="stylesheet" href="../../static/assetThree/css/animate.css">
	<!-- Icomoon Icon Fonts-->
	<link rel="stylesheet" href="../../static/assetThree/css/icomoon.css">
	<!-- Bootstrap  -->
	<link rel="stylesheet" href="../../static/assetThree/css/bootstrap.css">
	<!-- Theme style  -->
	<link rel="stylesheet" href="../../static/assetThree/css/style.css">
{#    <link href="../../static/assetOne/css/style.css" rel="stylesheet" type="text/css" media="all" />#}

	<!-- Modernizr JS -->
	<script src="../../static/assetThree/js/modernizr-2.6.2.min.js"></script>
	<!-- FOR IE9 below -->
	<!--[if lt IE 9]>
        <script src="../../static/assetThree/js/respond.min.js"></script>
        <![endif]-->
	</head>
	<body>

	<div class="fh5co-loader"></div>

    {% block page %}
	<div id="page">
	<nav class="fh5co-nav" role="navigation">
		<div class="container">
			<div class="row">
				<div class="left-menu text-right menu-1">
					<ul>
						<li><a href="{{ url_for('book.listPage') }}">书单</a></li>
						<li class="has-dropdown">
							<a href="{{ url_for('book.heart') }}">随心</a>
                            <!--可能有用-->
							<!--<ul class="dropdown">
								<li><a href="#">Web Design</a></li>
								<li><a href="#">eCommerce</a></li>
								<li><a href="#">Branding</a></li>
								<li><a href="#">API</a></li>
							</ul>-->
						</li>
					</ul>
				</div>
				<div class="logo text-center">
					<div id="fh5co-logo"><a href="{{ url_for('home.index') }}">主页</a></div>
				</div>
				<div class="right-menu text-left menu-1">
					<ul>
						<li><a href="{{ url_for('book.bookgreat') }}">浩瀚</a></li>
						<li><a href="{{url_for('page.analyse')}}">书海</a></li>
						<!-- <li class="btn-cta"><a href="#"><span>Login</span></a></li> -->
					</ul>
				</div>
			</div>

		</div>
	</nav>

	<header id="fh5co-header" class="fh5co-cover" role="banner">
		<div class="overlay"></div>
		<div class="container">
			<div class="row">
				<div class="col-md-10 col-md-offset-1 text-center">
					<div class="display-t">
						<div class="display-tc animate-box" data-animate-effect="fadeIn">
							<h1>随心</h1>
							<h2>输入任意关键字，给您推荐一本好评书籍<a target="_blank">如：推理、爱情等</a></h2>
							<div class="row">
                            {{ wtf.quick_form(form) }}
						<!--		<form class="form-inline" id="fh5co-header-subscribe">
									<div class="col-md-6 col-md-offset-3">
										<div class="form-group">
											<input type="text" class="form-control" placeholder="等待输入">
											<button type="submit" class="btn btn-default">随心之旅</button>
										</div>
									</div>
								</form> -->
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</header>

        <footer id="fh5co-footer" role="contentinfo">
            <div class="container">
                <div class="row copyright">
                    <div class="col-md-12 text-center">
                        <p>
                            <small class="block">Copyright &copy; 2021.BookLadder All rights reserved.</small>
                        </p>
                    </div>
                </div>

            </div>
        </footer>
    </div>
    {% endblock %}

    <div class="gototop js-top">
        <a href="#" class="js-gotop"><i class="icon-arrow-up"></i></a>
    </div>

    <!--待编辑-->
    <!-- jQuery -->
	<script src={{ url_for('static',filename = "assetThree/js/jquery.min.js") }}></script>
	<!-- jQuery Easing -->
	<script src={{ url_for('static',filename = "assetThree/js/jquery.easing.1.3.js") }}></script>
	<!-- Bootstrap -->
	<script src={{ url_for('static',filename = "assetThree/js/bootstrap.min.js") }}></script>
	<!-- Waypoints -->
	<script src={{ url_for('static',filename = "assetThree/js/jquery.waypoints.min.js") }}></script>
	<!-- Main -->
	<script src={{ url_for('static',filename = "assetThree/js/main.js") }}></script>

	</body>
</html>

Book_Ladder/web/templates/book/otherinfo.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="referrer" content="no-referrer">
    <title>Book Ladder</title>
    <link rel="shortcut icon" href="../../static/icon/fav.ico" type="image/x-icon"/>
    <link rel="icon" href="../../static/icon/fav.ico" type="image/x-icon"/>
    <link rel="stylesheet" href="../../static/assetFour/css/bootstrap.min.css">
    <link rel="stylesheet" href="../../static/assetFour/fontawesome/css/all.min.css">
    <link rel="stylesheet" href="../../static/assetFour/css/templatemo-style.css">
    <!--

    -->
</head>
<body>
<!-- Page Loader -->
<div id="loader-wrapper">
    <div id="loader"></div>

    <div class="loader-section section-left"></div>
    <div class="loader-section section-right"></div>

</div>
{% block banner %}
    <nav class="navbar navbar-expand-lg">
        <div class="container-fluid">
            <a class="navbar-brand" href="{{ url_for('home.index') }}">
                <i class="fas fa-book mr-2"></i>
                Book Ladder
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <i class="fas fa-bars"></i>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ml-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link nav-link-3" href="{{ url_for('home.index') }}">主页</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link nav-link-2" href="{{ url_for('book.listPage') }}">书单</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link nav-link-2" href="{{ url_for('book.heart') }}">随心</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link nav-link-1 " href="{{ url_for('book.bookgreat') }}">浩瀚</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link nav-link-4" href="{{ url_for('page.analyse') }}">书海</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
{% endblock %}

<!--展示处-->
{% block pre %}
<div class="container-fluid tm-container-content tm-mt-60">
    <div class="row mb-4">
        <h2 class="col-12 tm-text-primary" style="text-align: center">《{{ title }}》</h2>
    </div>
    <div class="row tm-mb-90">
        <div class="col-xl-8 col-lg-7 col-md-6 col-sm-12">
            <div class = "imgLink" style="text-align: center" >
            <img src="{{data['imglink']}}" alt="Image" class="img-fluid" style="width: 600px;height: 800px">
            </div>
        </div>
        <div class="col-xl-4 col-lg-5 col-md-6 col-sm-12">
            <div class="tm-bg-gray tm-video-details">
                <div class="mb-4 d-flex flex-wrap">
                    <div class="mr-4 mb-2">
                        <span class="tm-text-gray-dark">作者：</span><span class="tm-text-primary">{{ data['author'] }}</span><br/>
                        <span class="tm-text-gray-dark">译者：</span><span class="tm-text-primary">{{ data['trans'] }}</span><br/>
                        <span class="tm-text-gray-dark">出版社：</span><span class="tm-text-primary">{{ data['publish'] }}</span><br/>
                        <span class="tm-text-gray-dark">出版时间：</span><span class="tm-text-primary">{{ data['pubyear'] }}</span><br/>
                        <span class="tm-text-gray-dark">ISBN：</span><span class="tm-text-primary">{{ data['isbn'] }}</span><br/>
                        <span class="tm-text-gray-dark">书籍评分：</span><span class="tm-text-primary">{{ data['score'] }}</span>
                        <span class="tm-text-gray-dark">好评率：</span><span class="tm-text-primary">{{ data['sumper'] }}%</span><br/>
                        <span class="tm-text-gray-dark">评价人数：</span><span class="tm-text-primary">{{ data['commnum'] }}</span>

                    </div>
                </div>
                <div class="mb-4">
                    <h3 class="tm-text-gray-dark mb-3">价格</h3>
                   <a href="https://search.jd.com/Search?keyword={{ data['isbn'] }}&psort=2&click=0" target="_Blank">京东图书</a><p>{{ price['jd'] }}，详情请点击链接</p>
                    <a href="http://search.kongfz.com/product_result/?key={{ data['isbn'] }}&order=100&perfect=1" target="_Blank">孔夫子旧书</a><p>暂无数据，详情请点击链接</p>
                    <a href="http://search.dangdang.com/?key={{ data['isbn'] }}&act=input&sort_type=sort_xlowprice_asc#J_tab" target="_Blank">当当图书</a><p>{{ price['dd'] }}，详情请点击链接</p>
                    <a href="https://www.amazon.cn/s?k={{ data['isbn'] }}" target="_Blank">亚马逊电子书</a><p>暂无数据，详情请点击链接</p>
                </div>
                <div>
                    <h3 class="tm-text-gray-dark mb-3">标签</h3>
                    {% for tag in data['tags'] %}
                    <a href="https://book.douban.com/tag/{{ tag }}" class="tm-text-primary mr-4 mb-2 d-inline-block" target="_Blank">{{ tag }}</a>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

<footer class="tm-bg-gray pt-5 pb-3 tm-text-gray tm-footer">
    <div class="container-fluid tm-container-small">
        <div class="row">
            <div class="col-lg-8 col-md-7 col-12 px-5 mb-3">
                Copyright &copy; 2021.Company name All rights reserved.
            </div>
            <div class="col-lg-4 col-md-5 col-12 px-5 text-right">
                Designed by 聂琳予</a>
            </div>
        </div>
    </div>
</footer>

<script src="../../static/assetFour/js/plugins.js"></script>
<script>
    $(window).on("load", function() {
        $('body').addClass('loaded');
    });
</script>
</body>
</html>